chore: Add bigger instance for unbuntu focal
magma/ci-management pull request #31
Opened 2021-08-09 22:59 UTC by quentinDERORY

Signed-off-by: quentinDERORY <15911421+quentinDERORY@users.noreply.github.com>

2021-08-09 23:28 UTC, fabiopalumbo submitted a review, later dismissed

2021-08-10 00:10 UTC, jwagantall requested changes

2021-08-10 00:10 UTC, jwagantall commented on jenkins-config/clouds/openstack/vex/ubuntu2004-docker-8c-32g.cfg
> +LABELS=ubuntu2004-docker-8c-32g ubuntu1804-docker-8c-32g
2004 here.. instead of 1804

2021-08-10 16:49 UTC, jwagantall approved these changes

2021-08-10 16:49 UTC, merged